sudo: required
dist: trusty
language: java
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
jdk:
  - oraclejdk8
node_js:
  - "stable"
  - "6.0.0"
  - "7.0.0"
  - "8.0.0"
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - nvm install 6.9.5
install:
  - npm install
script:
  - npm test
cache:
  directories:
  - node_modules
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"